#!/bin/bash

DAYS_TO_KEEP=90
EASY_HOME=/home/craig/dockerdev/ca-super-wordpress

# cleanup first
find ${EASY_HOME}/backup -type f -mtime +${DAYS_TO_KEEP} -exec rm {} \;

docker exec super_dbServer /bin/bash -c "/usr/bin/mysqldump --databases wordpress | /bin/gzip > /tmp/super_dbServer.sql.gz"
docker exec -w / super_appServer tar zcf /tmp/super_appServer.tar.gz ./var/www/html
docker exec -w / super_mailHog tar zcf /tmp/super_mailHog.tar.gz ./var/mail

docker cp super_dbServer:/tmp/super_dbServer.sql.gz ${EASY_HOME}/backup/$(date +"%Y-%m-%d")-super_dbServer.sql.gz
docker cp super_appServer:/tmp/super_appServer.tar.gz ${EASY_HOME}/backup/$(date +"%Y-%m-%d")-super_appServer.tar.gz
docker cp super_mailHog:/tmp/super_mailHog.tar.gz ${EASY_HOME}/backup/$(date +"%Y-%m-%d")-super_mailHog.tar.gz

