FROM caapm/apmia:latest
COPY --chown=1000:1000 ./mysql.bundle.properties /usr/local/apmia/extensions/MySQL/bundle.properties
COPY --chown=1000:1000 ./nginx.bundle.properties /usr/local/apmia/extensions/NGINX/bundle.properties
USER root
